### ISSUE TITLE
Can't create new flags with pgsql

### ISSUE THREAD

**Issue by marceloboeira** [checkr/flagr#101]
Basically, I've started a pod on our cluster with sqlite, everything works well. However, when I switched to postgres nothing works anymore.

## Steps to Reproduce (for bugs)

1. Use a Postgres driver
2. Start the pod
3. Try to create a new flag
4. See it fail

<img width="1162" alt="screen shot 2018-03-09 at 16 17 16" src="https://user-images.githubusercontent.com/1898225/37214424-5c5d1abe-23b5-11e8-8d0b-5dc976923715.png">

```
time="2018-03-09T15:11:14Z" level=info msg="/go/src/github.com/checkr/flagr/pkg/handler/eval_cache.go:89sql: Scan error on column index 6: Cannot scan {} into Attachment type"
time="2018-03-09T15:11:14Z" level=info msg="/go/src/github.com/checkr/flagr/pkg/handler/eval_cache.go:89sql: Scan error on column index 6: Cannot scan {} into Attachment type"
time="2018-03-09T15:11:14Z" level=info msg="/go/src/github.com/checkr/flagr/pkg/handler/eval_cache.go:89sql: Scan error on column index 6: Cannot scan {} into Attachment type"
time="2018-03-09T15:11:14Z" level=error msg="reload evaluation cache error" err="sql: Scan error on column index 6: Cannot scan {} into Attachment type; sql: Scan error on column index 6: Cannot scan {} into Attachment type; sql: Scan error on column index 6: Cannot scan {} into Attachment type; sql: Scan error on column index 6: Cannot scan {} into Attachment type"
time="2018-03-09T15:11:14Z" level=info msg="/go/src/github.com/checkr/flagr/pkg/handler/eval_cache.go:89sql: Scan error on column ind
```

## Context
Trying to create a new flag with the Postgres driver

## Your Environment
* Version used (`flagr version`):  latest
* Operating System and version (`uname -a`): `Linux **-846cbb9848-nd8vt 4.4.111-k8s #1 SMP Sun Jan 14 19:32:08 UTC 2018 x86_64 GNU/Linux`
* Link to your project: --

**Comment by marceloboeira** [comment]
*Update*

I have switched the driver to mysql, with a mysql database of course, and now I don't experience that error.

**Comment by zhouzhuojie** [comment]
Thanks for reporting, I will take a look and see how to fix it for pgsql. Currently, we are using MySQL.
