### ISSUE TITLE
Monitoring / Heath Check 

### ISSUE THREAD

**Issue by marceloboeira** [checkr/flagr#102]
Considering that this would be a big part of the infrastructure (getting lots of public requests), it would be interesting to have a **health check endpoint**, in order to monitor the status. Even more if you consider autoscaling or anything of the sort (knowing when the pod is ready to receive traffic, or if its unhealthy and shouldn't receive much load). e.g.: https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-probes/

For even more control over the infrastructure, sending metrics to **statsd** would also be really awesome, in order to integrate with something like Datadog and investigate any latency with more precision.  

If its something that you guys think its okay I might be willing to work on PR for both.

**Comment by zhouzhuojie** [comment]
PRs are welcome!

1) for liveness check, if you want to work on it, you can start with the swagger definition of `/health` endpoint, and then implement it in `pkg/handler`
2) for statsd, you can take a look at the new relic middleware under `config/middleware.go`

Thanks!
