### ISSUE TITLE
Using Alpine 3.6 version as base image

### ISSUE THREAD

**Issue by sudhakso** [checkr/flagr#105]
We would like to consume Flagr for feature management. We don't want to ship any containers based on Debian due to a local policy. 
Instead, we would like to use "Alpine - 3.6" version - https://hub.docker.com/_/alpine/.

## Expected Behavior
Flagr should build and run on Alpine base image.

## Current Behavior
Untested

## Possible Solution
None that is offered in the checkr community.

## Context
Due to local policy, we cannot use Debian to distribute containers. And we would like Flagr to be built using Alpine.

## Your Environment
* Version used (`flagr version`): Latest
* Server type and version: X86_64
* Operating System and version (`uname -a`): Alpine 3.6 
* Link to your project: Not yet public

**Comment by zhouzhuojie** [comment]
Does your environment support multi-stage docker build? I'm thinking of moving the built binary to alpine3.6

**Comment by zhouzhuojie** [comment]
Related pr #107 #109

**Comment by sudhakso** [comment]
We were able to run flagr with alpine3.6.
