### ISSUE TITLE
Cannot build from source on macOS

### ISSUE THREAD

**Issue by OttoG** [checkr/flagr#106]
## Expected Behavior
Following the instructions at https://checkr.github.io/flagr/#/home the following commands should build flagr:

go get -u github.com/checkr/flagr
cd $GOPATH/src/github.com/checkr/flagr
make all

## Current Behavior

However, the “build” target in the Makefile (CGO_ENABLED=1 go build -o $(PWD)/flagr github.com/checkr/flagr/swagger_gen/cmd/flagr-server) fails with the following error:

…
Building flagr to /Users/…/go/src/github.com/checkr/flagr/flagr ...
\# github.com/checkr/flagr/pkg/mapper/entity_restapi/r2e
pkg/mapper/entity_restapi/r2e/r2e.go:13:25: undefined: models.PutDistributionsRequestDistributions
make: *** [build] Error 2

The macOS version is High Sierra 10.13.4 with Go version go1.10.1.

## Steps to Reproduce (for bugs)

1. Install build dependencies such as Go and Yarn.
2. Add binary directories for Go, global Go packages and Yarn to the path.
3. go get -u github.com/checkr/flagr
4. cd $GOPATH/src/github.com/checkr/flagr
5. make all

## Context

Tried to build from source according to instructions in the documentation.

## Your Environment

* Version used (`flagr version`): Code freshly fetched today from github.com/checkr/flagr
* Server type and version: macOS High Sierra
* Operating System and version (`uname -a`): Darwin ….local 17.5.0 Darwin Kernel Version 17.5.0: Mon Mar  5 22:24:32 PST 2018; root:xnu-4570.51.1~1/RELEASE_X86_64 x86_6

**Comment by zhouzhuojie** [comment]
Thanks for reporting, it was due to a upstream tooling (go-swagger) change. I've fixed in #108
