### ISSUE TITLE
Java SDK

### ISSUE THREAD

**Issue by cmaslen** [checkr/flagr#128]
Is there a Java SDK available?

**Comment by zhouzhuojie** [comment]
@cmaslen 

I think you can create the java SDK from swagger-cli. They have many options, I will look into what may fit for more use cases for a Java SDK.

For example

```
mkdir javaflagr
cd javaflagr
cp $GOPATH/src/github.com/checkr/flagr/docs/api_docs/bundle.yaml ./swagger.yaml
docker run --rm -v ${PWD}:/local swaggerapi/swagger-codegen-cli generate \ 
   -i /local/swagger.yaml \                                                
   -l java \                                                               
   -o /local/

# optional
docker run --rm -v ${PWD}:/local swaggerapi/swagger-codegen-cli generate \ 
   -i /local/swagger.yaml \                                                
   -l java \                                                               
   -o /local/
   -c /local/swagger_java.json   # configs for the generated code                       
```

**Comment by cmaslen** [comment]
Thanks for the response. I spotted the other client SDKs appear to be generated, but wasn't sure if you added stuff like local caching of flag values to cater for server outages etc.

**Comment by zhouzhuojie** [comment]
Yes, they are all generated. Client caching is not there yet. The current solution is to always have a sane default (e.g. the old feature as default) in code to handle any server outages when rolling out a new feature with Flagr.
