### ISSUE TITLE
Query params for findFlags not working

### ISSUE THREAD

**Issue by tomarad** [checkr/flagr#132]
## Expected Behavior
Setting query params on the findFlags API point should filter results.

## Current Behavior
findFlags returns all flags.

## Steps to Reproduce
We tried each query param, for example:
- https://try-flagr.herokuapp.com/api/v1/flags?description=tom
- https://try-flagr.herokuapp.com/api/v1/flags?limit=0

## Environment
We tried both the heroku app and the docker image from the README file.

I would open a PR with the fix myself but I lack the go/swagger knowledge..

Thanks!
Tom

**Comment by zhouzhuojie** [comment]
Thanks for reporting!

I just pushed the latest 1.0.6 to both try-flagr and the docker hub. It should work now.
