### ISSUE TITLE
Save Segment button is not clear if it saves the constraints or not

### ISSUE THREAD

**Issue by zhouzhuojie** [checkr/flagr#142]
![image](https://user-images.githubusercontent.com/658840/42474725-53d160e4-837d-11e8-968a-844f3c1ad493.png)

Not clear if the save segment button saves the constraints or not

**Comment by marceloboeira** [comment]
That's not working for me, I click on save and it doesn't update the constraints.

**Comment by chenquee** [comment]
It doesn't, I think it only saves changes to the segment description/rollout values.  

From what I could tell you have to click the checkbox next to the value of the constraint that you want to save.

**Comment by zhouzhuojie** [comment]
![image](https://user-images.githubusercontent.com/658840/45901314-58a94600-bd97-11e8-879a-d79f05b9f702.png)

I change the subtle "v" button to "save", hopefully it can help clarify what to click :). I guess the UI really needs some rework. Close the ticket now.
