### ISSUE TITLE
Kinesis Data Recorder Adapter

### ISSUE THREAD

**Issue by marceloboeira** [checkr/flagr#150]
At my company we use mostly Kinesis for streaming, so I would like to start working on a kinesis recorder; @zhouzhuojie wdyt?

**Comment by zhouzhuojie** [comment]
That's awesome, I've already reserved the switch case for more data recorders.

https://github.com/checkr/flagr/blob/master/pkg/handler/data_recorder.go#L24

**Comment by marceloboeira** [comment]
Closing since #151 got merged!
