### ISSUE TITLE
Question - How does a change in distribution affect existing users?

### ISSUE THREAD

**Issue by michaelduminy** [checkr/flagr#161]
Assume we have a feature flag `show_button` with variants `show` and `hide`.

A segment was on 100% rollout and distribution was 100% for `hide`. Now we want to increase the percentage of people who see the button. So we adjust it to be 90% `hide` and 10% `show`.

What happens to existing users who have already been evaluated as `hide`?
Does the change in distribution trigger a re-assessment of everyone in that segment when they evaluate a flag?

Thanks

**Comment by zhouzhuojie** [comment]
Very good question!

Flagr is stateless, and the variants assignment is based on the `entityID`. So, yes, if you change from 0/100 to 10/90, 10% of the `hide` users will get `show`. Note that it's deterministic at random.

We also have a doc at https://checkr.github.io/flagr/#/flagr_overview?id=flagr-running-example, let me know if it helps.

**Comment by michaelduminy** [comment]
Thanks for the quick response, @zhouzhuojie!

Ah the stateless part was what I was missing. So if I understand correctly, Flagr doesn't evaluate a flag and store the result somewhere, each evaluation occurs algorithmically and is deterministically random. Therefore there is no assessment to "re-trigger", the algorithm simply takes into account the percentage rollout and distribution of a segment during evaluation, so if any of the parameters change the results show up right away.

Is that accurate?

**Comment by zhouzhuojie** [comment]
That's right!

Flagr does log the evaluation results if you enable it - for data analytics purpose.

**Comment by michaelduminy** [comment]
Fantastic! Thanks again for the prompt response 🙇
