### ISSUE TITLE
Support for liveness check in flagr

### ISSUE THREAD

**Issue by Lexing** [checkr/flagr#165]
My understanding is that flagr is most likely to be used as a microservice in kubernetes. The server should only accepts requests after data loading (e.g. MySQL loading) is done 
Is it possible to add support for this ? or if it's already supported plz let me know 

thanks

**Comment by zhouzhuojie** [comment]
Yes, there's a `/health` check endpoint

https://checkr.github.io/flagr/api_docs/#tag/health
