### ISSUE TITLE
Getting path / was not found on new install

### ISSUE THREAD

**Issue by teewhey** [checkr/flagr#192]
Getting path / was not found on new install

## Expected Behavior
None 404 response perhaps?

## Current Behavior
Getting the following response from my browser

root@stretch:~# curl localhost:18000
{"code":404,"message":"path / was not found"}

## Context
I wanted to try to play around with the tool. Compiled from source and based on the documentation at https://checkr.github.io/flagr/#/README. Had to install certain extra stuff (build-essential, sqlite3, yarn) and need to install yarn from yarn repo.

root@stretch:~# flagr --port=18000 --host=0.0.0.0
INFO[0000] Serving flagr at http://[::]:18000

## Your Environment

* Version used (`flagr version`): no relevant output from this command. Installed based on official documention 10 minutes ago.
* Server type and version: vagrant
* Operating System and version (`uname -a`): Linux stretch 4.9.0-8-amd64 #1 SMP Debian 4.9.130-2 (2018-10-27) x86_64 GNU/Linux

**Comment by zhouzhuojie** [comment]
Thanks for the issue report. I think it's because `make all` didn't compile UI, so it returns 404 not found.

I've added the step and improve the docs to address this issue.
