### ISSUE TITLE
Granular access control for Flagr UI

### ISSUE THREAD

**Issue by kait2324** [checkr/flagr#195]
## Expected Behavior

As a financial organization, we must limit who has access to view and modify feature switches and A/B tests. 

The Flagr admin allows for simple access control via JWT, however, we would expect more granular role-base access control. We would like to control for who can read vs. who can write changes. Potentially even more granularity down to which items could be changed on an a/b test, such as distribution and segmentation. 

Organizations with multiple applications could also benefit from access to specific groups of flags. This would allow for large organizations needing different levels of administration control over who can update flags owned by their specific organization. 

## Current Behavior

JWT authorization is currently used for the Flagr admin and allows for a single role, authorized or not authorized.

## Possible Solution

Implement role-based access for updating/reading flags potentially using [casbin](https://github.com/casbin/casbin) or [goRBAC](https://github.com/mikespook/gorbac) for the admin page. Secondly, maybe add a construct of grouping in the FlagR admin -- and allow different access levels for flags owned by different organizations. For example:

---
Application A (read/edit roles for application A)
---
- flag A (read/edit roles for flag A && read/edit roles for application A)
- flag B (read/edit roles for flag B && read/edit roles for application A)
---
Application B (read/edit roles for application B) 
---
- flag A (read/edit roles for flag A && read/edit roles for application B) 
- flag B (read/edit roles for flag B && read/edit roles for application B)

**Comment by zhouzhuojie** [comment]
Thanks for opening the issue, this is an awesome feature request!

For now, we are still planning how to implement authorization in Flagr. Ideally, I think the solution should comply with the following requirements.

- Current JWT token design
- In general, how to do authorization as an open source project. It needs to be easily integrated into many enterprises' user sign-in flow.

The solution space is large enough, which makes the design of authorization, not a trivial task.
For example, if we go with casbin, we need to plan on

1. How to get `roles`, `permission`, and `permission group` from JWT token?
2. How to create/update/delete access rules?

If you have further suggestions on the implementation, feel free to let us know. 

For now, I'd recommend that you can build your own flagr-admin-proxy service, that does the authentication and authorization, and proxy the request to flagr API. And then points Flagr UI's API URL to your own flagr-admin-proxy.
