### ISSUE TITLE
Support Prometheus

### ISSUE THREAD

**Issue by zhouzhuojie** [checkr/flagr#196]
Support Prometheus for better observability

**Comment by jasongwartz** [comment]
@zhouzhuojie We're starting to test out flagr at Ecosia, and we use prometheus monitoring heavily, so I'd be interested in taking this issue if it still needs doing. Is it just a matter of exporting metrics for the http handlers?

**Comment by zhouzhuojie** [comment]
Yes, metrics for the HTTP handlers could be the first step! Also, for the evaluation result, I think we can export metrics just like what we are doing for datadog.
https://github.com/checkr/flagr/blob/master/pkg/handler/eval.go#L185-L200
