### ISSUE TITLE
Empty Arrays Returned for Segments and Variants on GET flags endpoint

### ISSUE THREAD

**Issue by corytak** [checkr/flagr#199]
## Expected Behavior

Calling the GET /flags endpoint would return a collection of segments and variants related to each flag

## Current Behavior

GET /flags endpoints returns empty arrays for segments and variants regardless of whether or not they're present

## Possible Solution

If there's concern about the size of the response, could potentially have a summary flag as a query parameter that returns a list of flags without all of their child component details

## Steps to Reproduce (for bugs)

1. Navigate to [Live Demo Site](https://try-flagr.herokuapp.com/#/)
2. Open Dev Tools in Chrome and navigate to Network tab
3. Choose flags request and preview response
4. Note that segments and variants are empty

![image](https://user-images.githubusercontent.com/9749465/50404862-1dd5f600-076a-11e9-89cf-549fbfa1fcbe.png)

## Context

I'm attempting to migrate feature flags and their state from lower environments to higher environments in a code first fashion. Checking the state of existing flags, variants, and segments would make this process easier. As a work around, I can GET /flags and then GET the segments for each flag individually, but would prefer to be able to make one request up front. 

## Your Environment

* Version used (`flagr version`): 1.0.12
* Server type and version:
* Operating System and version (`uname -a`):
* Link to your project: Private Repo

**Comment by zhouzhuojie** [comment]
Thanks for reporting, I didn't include the preloaded segments and variants to save some time when rendering the frontpage list.

What do you think of adding a parameter like `GET /flags?preload=true` to get all the segments and variants, while at the same time, keep the current behavior of `GET /flags`?

**Comment by corytak** [comment]
I think that sounds like a great plan
