### ISSUE TITLE
Retry DB Connections

### ISSUE THREAD

**Issue by crberube** [checkr/flagr#207]
Related to #110

## Expected Behavior
When starting the application, if a DB connection can not be initiated, the application should retry before failing and terminating.

## Current Behavior
If the application fails to connect to a DB it immediately exits.

## Possible Solution
A simple solution could be to allow for a small number of connection attempts at a fixed interval before calling ```logrus.Fatal```. A more complicated solution could involve exponential backoff or and/or a configurable wait period before failure.

## Steps to Reproduce
Configure Flagr to use PostgreSQL or MYSQL database.
Start Flagr before starting database server.

## Context
We have Flagr running in Kubernetes on Google Cloud Platform. It is configured to use a PostgreSQL database. In order to access that database, we have a sidecar which runs Cloud SQL Proxy. When deploying the server, Flagr attempts to access the database while the sidecar container is still initializing. This forces Kubernetes to restart the Flagr container upon which it is able to connect to the database through the proxy.

While this approach technically works, it seems like Flagr should be able to tolerate a small delay that could occur when getting SQL servers running in a containerized environment.

**Comment by zhouzhuojie** [comment]
Makes sense. I just quickly added a retry, let me know what do you think.

**Comment by crberube** [comment]
Added a couple of comments to your PR. Looks good
