### ISSUE TITLE
Release Schedule

### ISSUE THREAD

**Issue by crberube** [checkr/flagr#211]
Hi,

Just curious how you determine when to put together new releases and push them to Docker Hub. I expect that I will be getting more involved with this project and it would be nice to have an idea of when things are expected to go from master into an official image.

**Comment by zhouzhuojie** [comment]
I can run a release now.

I'm manually cutting release tags and pushing to dockerhub. 

Commits are usually not breaking changes in the recent months, so we don't have strict rules to follow when to cut a release. Any good advice on this? We can do release every 1-2 months. If you have important new features that you want in the official image, feel free to open an issue.

Add btw, we are deploying master to production, so most of the features (e.g. we don't use kineses) should be production ready.

**Comment by crberube** [comment]
Great thanks.

In the absence of a continuous delivery process, I've found that having some sort of schedule such as releasing on a certain day on a bi-weekly basis to be a good way to keep things consistent and avoid too many changes from happening at once. That being said, I'm not trying to impose any sort of schedule or disrupt your process — we can certainly take an issue-based approach!

It's good to know that you are comfortable deploying mater to prod, we can certainly create our own images based off master as well. It's just easier to pull them from Docker Hub if possible and would make sure anyone else who is doing so has a reasonably up-to-date version.

**Comment by zhouzhuojie** [comment]
Close this issue for now. 

@crberube we have some security rules to workaround a github bot user, which is required from DockerHub. Therefore, right now the builds on https://hub.docker.com/r/checkr/flagr/tags are not automated and fully transparent with Dockerfile tagged. I will update here if I have some new solutions to share.
