### ISSUE TITLE
[feat] restore deleted flags

### ISSUE THREAD

**Issue by zhouzhuojie** [checkr/flagr#215]
Some flags are sensitive, if it's deleted, make sure it's also easy to restore as well. Currently, in gorm, everything is soft deleted. I think this feature will need the following changes:

- UI front page, to not only show the current flags, but also a section to show deleted flags.
- A new parameter in `GET /flags?deleted=true` to get deleted flags
- A new route `POST /flags/<id>/restore` to restore deleted flags
- A new UI button to restore deleted flags

**Comment by Shailendra1118** [comment]
@zhouzhuojie By `POST /flags/<id>/restore` do you mean by creating a new flag with values same as deleted.
