### ISSUE TITLE
Swagger Codegen generated PHP SDK

### ISSUE THREAD

**Issue by EspadaV8** [checkr/flagr#220]
I noticed that you offered some SDKs but none for PHP. I checked the ones you do have and saw that they are all auto-generaged using swagger-codegen. I copied some of the existing work and updated it to generate a PHP version - https://github.com/EspadaV8/phpflagr.

I'm happy for you to take this if you'd like it to be part of the main flagr namespace. If not, would you mind having a look at it and seeing if I have missed anything that should be included. I copied the `swagger.yaml` and used the `Makefile` and `swagger_py.json` files as a base for the ones in the repo.

I was wondering if you had something set up to automatically update the `swagger.yaml` files in your repositories when you build a new version of flagr?

**Comment by zhouzhuojie** [comment]
Thanks! Feel free to generate the php client SDK as you want. Make sure you

- Copy the latest compiled swagger file from https://github.com/checkr/flagr/blob/master/docs/api_docs/bundle.yaml
- For client SDK's version, we recommend to use the same version as in the bundle yaml file.
