### ISSUE TITLE
Flagr-UI Cannot Resolve Static Assets when using FLAGR_WEB_PREFIX environment variable

### ISSUE THREAD

**Issue by corytak** [checkr/flagr#222]
## Expected Behavior
It is expected that if `FLAGR_WEB_PREFIX` environment variable is used that the UI will be able to retrieve its static assets (js/css files)

## Current Behavior
In the index.html, all static resources are being retrieved starting at the root (e.g. `/static/some.js` )

## Possible Solution
Wondering if it's possible to either set `base href` value to the value of FLAGR_WEB_PREFIX or to make references to assets relative rather than absolute in the web pack config. e.g. `static/some.js` instead of `/static/some.js`. 

## Steps to Reproduce (for bugs)

1. Run `docker run -it -p 18000:18000 -e FLAGR_WEB_PREFIX='/foo' checkr/flagr`
2. Navigate in web browser to `localhost:18000/foo` (ensure cache is cleared)
3. Note that index.html resolves correctly but all of the js/cs files receive 404s

![image](https://user-images.githubusercontent.com/9749465/53252252-b231db80-367b-11e9-9054-bcd73a739525.png)

## Context
We are unable to use the flagr-ui behind our load balancer where the uri looks something like
```www.domain.com/foo/flagr```

## Your Environment

* Version used (`flagr version`):1.0.13 
* Server type and version:
* Operating System and version (`uname -a`): Windows
* Link to your project:

**Comment by zhouzhuojie** [comment]
Thanks for reporting, pr to fix: https://github.com/checkr/flagr/pull/223

**Comment by corytak** [comment]
Wow that was fast! Thank you for making something so great.
