### ISSUE TITLE
Disable enableDebug Propery for Evaluation Transactions

### ISSUE THREAD

**Issue by fenriskiba** [checkr/flagr#228]
There does not seem to be a way to disable the enableDebug option for Evaluations in a Production environment. It seems like that could lead to some data about the A/B Tests being run to leak to external users.
Is there any plan to create a config to disable that?

**Comment by zhouzhuojie** [comment]
Sounds like a good env setting to add. PRs are welcome!

**Comment by zhouzhuojie** [comment]
I guess a more interesting question is how to show debug information when it's disabled globally, I know sometimes I would want to see it without changing the global setting.

When you expose Flagr to external users, do you have a gateway or reverse proxy? Maybe worth building a simple layer there to remove the `enableDebug` field from the external requests.

**Comment by fenriskiba** [comment]
I would worry about a performance hit from removing it at a proxy or gateway level, but it could work. It would also probably add a lot of complexity to the maintenance effort though.

Really, I would want to handle debugging with multiple environments. Debugging against Production would be problematic for a lot of apps (maybe not for Flagr as much, but it can be helpful to be consistent), so I would try to recreate the problem in a Non-Prod environment that has debugging enabled. If I couldn't figure out how to do that (which is fairly rare in my experience, but definitely not impossible), then we would likely have to consider the priority of the issue vs changing the global setting.

**Comment by zhouzhuojie** [comment]
@fenriskiba #235
