### ISSUE TITLE
Flag Note Support

### ISSUE THREAD

**Issue by crberube** [checkr/flagr#230]
My team and I were talking about how we want to have some documentation for the different A/B tests we are running. I thought it would be useful if the flag page had a "Notes" section so that relevant details could be viewed right in the Flagr UI. It could be something as simple as a text area or even allow for some markdown. Opening this issue to gauge interest in this idea.

**Comment by zhouzhuojie** [comment]
Good idea!

**Comment by pacoguzman** [comment]
This can be closed as the references PR was already merged?
