### ISSUE TITLE
Variant Attachment JSON Support

### ISSUE THREAD

**Issue by crberube** [checkr/flagr#231]
I notice that right now for simplicity reasons variant attachments only support string/string key/value pairs. This works reasonably well, but there are some tests that would be made much easier if we were able to simply return a full JSON object. I envision something like the JSON editor used in the debug console which could (optionally?) be used to set a variant attachment. Is this something that should be reasonably achievable or are there some complications that could occur as a result of supporting this?

**Comment by yosyad** [comment]
@saary And I worked on this feature in the past week and it was merged. Now you can enjoy of having real json as variant attachment! I think that this issue can be closed.

**Comment by zhouzhuojie** [comment]
Thanks to @yosyad and @saary. Released in 1.1.3.
