### ISSUE TITLE
Fatal Error when Unable to Reach Kafka

### ISSUE THREAD

**Issue by fenriskiba** [checkr/flagr#244]
We have encountered an error which caused Flagr to fatally crash and restart the container whenever it tries and fails to send data to Kafka.
Every time an evaluation is processed and cannot reach Kafka, we receive the following error, the evaluation fails, and the Flagr container crashes and is forced to restart.

`time="2019-03-20T20:33:39Z" level=fatal msg="Failed to start Sarama producer:" kafka_error="kafka: client has run out of available brokers to talk to (Is your cluster reachable?)"`

We cannot recreate the issue in a local Docker environment, but it is extremely consistent on our OpenShift server.

**Comment by zhouzhuojie** [comment]
In your production server, can you try the kafka connection with other clients?

I think I can make the fatal happen at the startup time, instead of lazily loaded at the evaluation time. So you can catch the connection issue earlier.

**Comment by fenriskiba** [comment]
Yes, we can connect to Kafka from other clients and everything is working fine on that end. Our current issues are mostly a result of needing to set up the right security configurations.

Our concern is more around any future Kafka downtime. If Kafka has downtime for an update, or a change made in a firewall unexpectedly causes the connection to start getting blocked, we would rather Flagr keep running so that users can keep being assigned experiences. Then we can run some batch evaluations for the relevant users to populate the analytics data lost while we resolve the issue.  
Towards that end, causing the crash at startup may actually make the problem worst, because, as things currently stand, we can work around the issue by disabling Data Records on any Flags with it enabled. If Flagr crashes at startup, we won't be able to do that.

**Comment by zhouzhuojie** [comment]
The fatal crash only happened once when it establishes the connection for the producer, and the producer is a singleton. All future errors after the producer is created will not crash the application, instead, it will log with errors and let the application continue.

https://github.com/checkr/flagr/blob/master/pkg/handler/data_recorder_kafka.go#L32-L78

**Comment by fenriskiba** [comment]
Okay, I see that makes sense then. I was misunderstanding how some of how Flagr was handling it was handling it. Thanks!
