### ISSUE TITLE
Release 1.1.1 is missing from Docker Hub

### ISSUE THREAD

**Issue by EspadaV8** [checkr/flagr#251]
Just tried to update one of our projects to the latest release and got an error, checked Docker Hub and saw that 1.1.1 isn't listed (https://hub.docker.com/r/checkr/flagr/tags), last release was 1.1.0. Any chance of getting 1.1.1 tagged and pushed?

**Comment by zhouzhuojie** [comment]
Thanks for the reminder, released 1.1.1 and the demo website now. https://hub.docker.com/r/checkr/flagr/tags
