### ISSUE TITLE
Strange characters coming through Kinesis stream

### ISSUE THREAD

**Issue by smithatlanta** [checkr/flagr#267]
![Screen Shot 2019-06-03 at 12 37 59 PM](https://user-images.githubusercontent.com/351756/58818748-9a63df00-85fc-11e9-9932-1dfc20fc65c4.png)

I just added the following flags to enable the Kinesis Recorder and I can see rows flowing over but when I hook up the stream to Kinesis Analytics I'm seeing a bunch of what looks like binary data flow over(per the screen shot above.
{
  "name": "FLAGR_RECORDER_TYPE",
  "value" : "kinesis"
},
{
  "name": "FLAGR_RECORDER_KINESIS_STREAM_NAME",
  "value": "test-flagr-stream"
},
{
  "name": "FLAGR_RECORDER_FRAME_OUTPUT_MODE",
  "value" : "payload_raw_json"
}

I'm using the 1.1.3 release from docker hub running on AWS Fargate.

**Comment by zhouzhuojie** [comment]
Hi @smithatlanta , while I'm looking into it, can you show us how exactly did you get/print the log in the first place?

CC @marceloboeira, did you see similar things from Kinesis? I don't have kinesis setup from AWS currently, I can try to find some time to see if I can reproduce this.

**Comment by smithatlanta** [comment]
This screen shot was after I created the stream in Kinesis Data Streams and attempted to connect that stream to Data Analytics and discover the Schema.

This is the Data Analytics screenshot:
![Screen Shot 2019-06-03 at 1 46 55 PM](https://user-images.githubusercontent.com/351756/58822766-4100ad80-8606-11e9-80a2-06edaaa8cad0.png)

And this is after clicking the Discover Schema and then clicking Edit Schema.
![Screen Shot 2019-06-03 at 1 50 03 PM](https://user-images.githubusercontent.com/351756/58822897-84f3b280-8606-11e9-96dd-74d47f071534.png)

It may actually be an issue with Data Analytics but I just wanted to report it if anyone else tried to do this.

**Comment by raviambati** [comment]
@smithatlanta can you change encoding to UTF-8 and try again? JSON requires UTF-8 encoding usually.

**Comment by marceloboeira** [comment]
Unfortunately I can’t help much, my setup was mainly using firehouse and I haven’t faced this issue. It seems to be encoding related, I’m to say that the `record encoding` has something to do with it for sure.  If it was flagger related we would’ve seen it as well. Unless the flagger encoring is somehow OS dependent...

**Comment by smithatlanta** [comment]
@marceloboeira / @raviambati I'll double check that I'm sending using UTF-8 in the morning.  That makes the most sense to me based on what I'm seeing.

**Comment by marceloboeira** [comment]
The screenshot shows windows 1252 encoring, on the steaming side...

**Comment by smithatlanta** [comment]
So it must be something with the AWS Schema Discovery tool in Kinesis Analytics.  I tried sending UTF-8 encoded API calls and it still came up with binary characters.  So I verified things by hooking it up to a firehose and sent it to an S3 bucket and it looks clean.
