### ISSUE TITLE
UI appears to delete the wrong constraint

### ISSUE THREAD

**Issue by sesquipedalian-dev** [checkr/flagr#290]
In the Flagr UI, if you have multiple constraints on a segment and delete one, it appears to delete the wrong constraint.  If you reload the page, it shows that the correct constraint was deleted after all. 

## Expected Behavior
When you delete a constraint in the UI, that constraint should not be listed and the other constraints already present should remain.

## Current Behavior
When you delete a constraint in the UI, that constraint is still visible until you reload the page. 

## Possible Solution
not sure

## Steps to Reproduce (for bugs)
1. https://try-flagr.herokuapp.com/#/flags/1
2. Add a constraint (contents don't seem to matter) to the default segment, and reload the page
3. Delete the constraint you added
4. Observe that the original 'state' constraint is missing, and the one you added still appears to be there
5. Reload the page and observe that actually the deletion was properly saved in the DB

## Context
Small confusion when editing stuff in the UI. 

## Your Environment
* Version used (`flagr version`): 1.1.4
* Operating System and version (`uname -a`): OS X
* Browser: Chrome

**Comment by rclayton-the-terrible** [comment]
We noticed the same issue today.  The correct constraint is actually deleted on the backend, but the UI shows a different constraint removed.  I'm not sure, but it's either the top-most constraint is removed in the UI, or if it's off-by-one.
