### ISSUE TITLE
Variant Distribution does not work

### ISSUE THREAD

**Issue by tkanos** [checkr/flagr#293]
When I have a Segment with the following distribution
- 50% Variant A 
- 50% variant B,

PostEvaluation only returns me variant A

## Expected Behavior

I should get 50% of the time variant A and the other 50% of the time variant B

## Current Behavior

I only get varaint A

## Steps to Reproduce (for bugs)

1. Go to https://try-flagr.herokuapp.com/#/flags/1
2. Use the debug console to send a request 
3. Change the request context to have 
```
"state":"CA"
```
you should en up with the following request  : 
```
{
  "entityID": "a1234",
  "entityType": "report",
  "entityContext": {
    "state": "CA"
  },
  "enableDebug": true,
  "flagID": 1,
  "flagKey": "kmmcd1nsd6ze56chh"
}
```
4. Post 10 times, you should receive 10 "variantKey": "blue"  instead of ~5 blue ~5 red 

## Context

I'm trying to make my company uses flagr.

## Your Environment

* Version used (`flagr version`): try-flagr.herokuapp.com one
* Server type and version: try-flagr.herokuapp.com one
* Operating System and version (`uname -a`): try-flagr.herokuapp.com one
* Link to your project:

**Comment by tkanos** [comment]
Never mind, I get that I had to change the entityID.

Sorry.

**Comment by zhouzhuojie** [comment]
This is by design to keep the rollout persistent. The entropy and randomness should come from the population of `entityID`. We have some documentation from here https://checkr.github.io/flagr/#/flagr_overview.
