### ISSUE TITLE
Need Feeedback on a client acting as a local evaluator

### ISSUE THREAD

**Issue by tkanos** [checkr/flagr#298]
I plan to heavily use flagr, unfortunately at  x Billions of request per day, goflagr (that I use as client) takes too much time.

To fix that network issue, I created https://github.com/tkanos/flagrc,
That act as a local evaluator (for all evaluation request except the EntityID ones) :
- load and cache the flags (locally in client side)
- execute evalFlag to evaluate (in client side)
- if it's an entityID request, it fallback to goflagr (that ask to the server)

Do you think that the client/evaluator is a good idea ?
Do you see concepts that can prevent that to fully work ?

If you look at the code (https://github.com/tkanos/flagrc), you will see that I only use flagr functions, to act as much as evaluator as possible : 
- for the Cache
- for the entities
- for all functions used by evalFlag and evalSegment
The only exception being evalFlag and evalSegment that I copied/paste in my own code (because this functions are not public in flagr)
Can you make them public I can rely completely on flagr code ?

Thanks for the feedback.

**Comment by zhouzhuojie** [comment]
Very interesting use case, we didn't think of embedding flagr as a go package for other go applications before. I think it makes sense and there's a demand for client evaluation. Thanks for the library, and feel free to open PR if you want some functions to be public.

 In general, I'd like to have a clear picture of client-side evaluation, so here are some open questions:
- How do we handle client side vs server side evaluaiton in general?
- What feature parity we'd like to keep between client side and server side?
- How do we sync flag updates to client side?
- How do we keep client side update to date with new evaluation logic from server side?
- How do we support languages other than go?

This could be a good starting point. Originally I was thinking of sidecar deployment approach, or compile flagr client to wasm and can be included in any language that can support wasm.

**Comment by tkanos** [comment]
**- How do we handle client side vs server side evaluaiton in general?**
For now all that is not EntityID, is done in client side. (once I finish that part, I will maybe do the EntityID configurable in client side as well)

**- What feature parity we'd like to keep between client side and server side?**
The server is only use for : 
- EntityID evaluation (at least for now)
- Evaluation of client that doesn't have the local evaluator
- Update all the others evaluator (aned client as well) thanks to the endpoint /export/eval_cache/json.

**- How do we sync flag updates to client side?**
I use the json_http flagr mechanism, that will call each **EvalCacheRefreshInterval** (3 sec by default) the server **/export/eval_cache/json** endpoint.

**- How do we keep client side update to date with new evaluation logic from server side?**
For flagrc, I took flagr as a package, so If flagr changes its logic, most of the time, I only need to synchronize the modules.

**- How do we support languages other than go?**
Not being part of checkr, I fortunately don't have to answer that question :D, But if I need the same behavior for one of the language I know, I think I will have to implement all by myself (not being able to use flagr internal package/logic)

So I'm finishing the flagrc code  (https://github.com/tkanos/flagrc), when it's done : 
- I will test it, in some of my internal projects
- maybe do the EntityID evaluation (confgurable) in client side
- Dinr the beer of victory :D

**Comment by tkanos** [comment]
Hello @zhouzhuojie 
So after some tests on github.com/tkanos/flagrc, here are my conclusions.


As you know I have to handle billions of connection per day, and I should be fast, unfortunately with goflagr client, I had to have x*10 flagr servers (each server costing y$), to handle billions of request. And it was slow (20 ms/op). 

Using github.com/tkanos/flagrc, I only need 1 flagr server. (so economy of [(x*10*y)-y]$), and it is super fast (4000 ns/op) soI can handle even more connection.

|   | goflagr  | flagrc  |
|---|---|---|
| servers  | x*10  | 1  |
| cost  | x*10*y  | y  |
| speed   |  20 ms | 4000 ns  |

For now I only did my tests for request without EntityID, Tomorrow I should be able to do the tests using EntityID (but it should be ok), and release the final version of flagrc (with all features).

btw, I am absolutely fan how you handle the Distribution.
