### ISSUE TITLE
[question/feature request] Allow slashes (/) in flag keys

### ISSUE THREAD

**Issue by Cull-Methi** [checkr/flagr#315]
## Expected Behavior

Flags with the `/` character should be able to be made

## Current Behavior

`util.IsSafeKey()` rejects flags with a slash due to the `keyRegex` defined as `^[\w\d-]+$`

## Possible Solution

Change the regex to allow slashes

## Context

Trying to namespace flags with slashes.

## Question

Is there a technical reason for the lack of slashes here? If not, it should be a fairly innocuous change that I'd gladly put up a PR for

**Comment by zhouzhuojie** [comment]
I see, are you going to use `/` as a higher order of separator than `-`? I think it makes sense to change the regex to fit this.

**Comment by Cull-Methi** [comment]
Yeah, the plan is to encourage our users to namespace things in intelligent ways. Something like

`service-name/flag1`
`service-name/flag2`

or even

`team-name/service-name/flag1`

**Comment by Cull-Methi** [comment]
I'm working on the necessary change to this now - the simplest route is to change the regex to `^[\w\d-/]+$`. This allows for leading and trailing slashes as well. Is that an issue, do you think?

**Comment by zhouzhuojie** [comment]
I think that's ok, people may like some file-path style if they choose to.

**Comment by Cull-Methi** [comment]
Closed by #316
