### ISSUE TITLE
[Bug] When attempting to save an invalid JSON blob for a variant attachment, flagr reports success

### ISSUE THREAD

**Issue by Cull-Methi** [checkr/flagr#324]
## Expected Behavior

When invalid JSON is entered into a variant attachment and then the user hits "save" flagr should alert them that the JSON is invalid and that their change wasn't saved

## Current Behavior

When hitting save w/ invalid JSON flagr reports that it was successfully updated. Flagr doesn't actually save the bad json, and on a refresh you'll see that the JSON has been "reverted" to the state before you tried to save bad JSON

## Possible Solution

Haven't looked through the code surrounding this just yet, but probably need to return a 4xx error and then I think the regular flagr UI error handling will handle it appropriately?

## Steps to Reproduce (for bugs)

1. Make a new flag with variants
2. Add a variant attachment
3. Save it with valid JSON
4. Refresh, input bad JSON
5. Hit save, observe that flagr seems happy about it
6. Refresh, your change will not have been saved

## Your Environment

* Version used (`flagr version`):
* Server type and version:
* Operating System and version (`uname -a`):
* Link to your project:

**Comment by zhouzhuojie** [comment]
Hi, looks like a UI bug, so when the json is not valid, the value is not bound to the attachment value. 
![image](https://user-images.githubusercontent.com/658840/76472856-01949800-63b4-11ea-92b9-b7661a0099e9.png)

Maybe we should prevent users from submitting the "Save Variant" button when the attachment json is not valid.
