### ISSUE TITLE
Question: Flags Usage Stats

### ISSUE THREAD

**Issue by kolbis** [checkr/flagr#325]
Great project!

Is it possible to track flags, variant usage? For example, how many hits to a given fag and a given variant? Are those stats exported to 3rd party provider?

**Comment by marceloboeira** [comment]
Hey @kolbis 

You can check the architecture overview, Flagr itself does not store stats but you can produce the events to a stream/pubsub and then have consumers attached to it.

Overview: https://checkr.github.io/flagr/#/flagr_overview

Configuration: https://checkr.github.io/flagr/#/flagr_env
You can choose between Kafka/Kinesis and Google PubSub

**Comment by zhouzhuojie** [comment]
Thanks @marceloboeira , exactly what you said.

Flagr supports logging to a set of data recorders, for example, kafka, pubsub, kinesis.
Flagr also supports Datadog and NewRelic, if you are into the realtime monitoring.

**Comment by kolbis** [comment]
@zhouzhuojie where can i find more information about datadog integration?

**Comment by marceloboeira** [comment]
@kolbis you ca find it here: https://checkr.github.io/flagr/#/flagr_env

The statsd client is datadog compatible:
```
    // StatsdEnabled - enable statsd metrics for all the endpoints and DB operations
    StatsdEnabled        bool   `env:"FLAGR_STATSD_ENABLED" envDefault:"false"`
    StatsdHost           string `env:"FLAGR_STATSD_HOST" envDefault:"127.0.0.1"`
    StatsdPort           string `env:"FLAGR_STATSD_PORT" envDefault:"8125"`
    StatsdPrefix         string `env:"FLAGR_STATSD_PREFIX" envDefault:"flagr."`
    StatsdAPMEnabled     bool   `env:"FLAGR_STATSD_APM_ENABLED" envDefault:"false"`
    StatsdAPMPort        string `env:"FLAGR_STATSD_APM_PORT" envDefault:"8126"`
    StatsdAPMServiceName string `env:"FLAGR_STATSD_APM_SERVICE_NAME" envDefault:"flagr"`
```
