### ISSUE TITLE
Find Flags enabled=false returning Enabled Flags

### ISSUE THREAD

**Issue by fenriskiba** [checkr/flagr#342]
For some reason, when calling `/api/v1/flags/?enabled=false` Flags that are enabled are being returned.

Setting `enabled=true` works as expected, but false seems to be off.

## Expected Behavior
Calling the Find Flags API with `enabled=false` in the query string should only return flags that are disabled.

## Current Behavior
Calling the Find Flags API with `enabled=false` in the query string returns all flags.

## Your Environment
Flagr v1.1.7 hosted in Red Hat OpenShift (though I also found the same issue in local docker).

**Comment by zhouzhuojie** [comment]
Thanks for the bug report, my first guess is that gorm didn't send "zero" values with the actual query run in the database.

https://github.com/checkr/flagr/blob/916baf2707db8feb0704ab606b31e978e2387b93/pkg/handler/crud.go#L77-L79

Will work on a fix soon.
