### ISSUE TITLE
[feat] Support additional characters in keys

### ISSUE THREAD

**Issue by dcramer** [checkr/flagr#347]
In our particular scenario we use a `:` to denote a separation of concern in features. In other cases we also use a `.` notation.

e.g. feature=`organization:create` or feature=`auth.register`

It'd be nice if Flagr could support these same kind of naming conventions, as I'm guessing there's no actual reason not prevent those two characters in key names currently.

**Comment by zhouzhuojie** [comment]
I think `:` and `.` are fine, and we recently added `/` to the characters set. The only concern is that if flagKey is going to be used in the URL path in the future, we may need to do some URL % encoding.
