### ISSUE TITLE
docker - cant listen on localhost

### ISSUE THREAD

**Issue by awcoding** [checkr/flagr#357]
can't get checkr/flagr working with `-p 127.0.0.1:18000:18000`.
I tried it with both `-e HOST=0.0.0.0` and `-e "HOST=127.0.0.1"`. No joy.

am i missing something? I tried to workaround but firewall on this box is hellishy complicated and that option appears less accessible.

**Comment by marceloboeira** [comment]
I got it working here with:

```
docker run -it -p 18000:18000  checkr/flagr
```

I don't believe you need to put the host before the port.

**Comment by awcoding** [comment]
Thank you @marceloboeira. My goal is to listen on the localhost interface instead of all interfaces. Prefixing the 127.0.0.1 is docker's convention on how to do that. But it doesn't seem to be working for this case.

**Comment by marceloboeira** [comment]
Interesting, I've never had a usecase for that. I've tried here:

```
docker run -p 127.0.0.1:18000:18000 checkr/flagr
docker run -p 0.0.0.0:18000:18000 checkr/flagr
```

both worked.

**Comment by awcoding** [comment]
Yeah, it worked for me too just now. I don't know how but I must have screwed something up earlier. Closing issue.

**Comment by awcoding** [comment]
For interest this is almost certainly where I screwed up earlier:
`ssh -L 18000:127.0.0.1:18000 root@example.org`
NOT
`ssh -L 18000:example.org:18000 root@example.org`
