### ISSUE TITLE
Different API description in same flagr version (docker vs github)

### ISSUE THREAD

**Issue by maximmarakov** [checkr/flagr#373]
Pulling from docker 1.1.9 i have API without tags, but in github i saw API with tags in the same version. 
Api description from docker container 
![image](https://user-images.githubusercontent.com/36736392/86011025-9e4b7600-ba35-11ea-879b-b65d51dffc78.png)
API at https://checkr.github.io/flagr/api_docs/
![image](https://user-images.githubusercontent.com/36736392/86011197-d6eb4f80-ba35-11ea-936a-802155b6e262.png)

**Comment by zhouzhuojie** [comment]
Yes, unreleased features are in the master branch that goes to https://checkr.github.io/flagr/api_docs/, which has the previous version. We may want to use something like `x.y.z-pre` for master branch api docs.

`tags` will be released with 1.1.10 soon.

**Comment by zhouzhuojie** [comment]
1.1.10 is released.
