### ISSUE TITLE
REST apis support

### ISSUE THREAD

**Issue by rsahoo752055** [checkr/flagr#385]
Is there any REST api support available where caller service will provide flagID, variant and segment detail in rest api call and flagr will give return value as true, if variant and segment details are present for inputted flagID and return false, if not.

**Comment by brasilikum** [comment]
Hey @rsahoo752055,

Is this the endpoint you are looking for?
https://checkr.github.io/flagr/api_docs/#operation/postEvaluation

You can create the variants "on" and "off". Only if the segment details are present you return "on", else "off".

Does that answer your question?
