### ISSUE TITLE
Feat: Support semantic versioning in Constraint

### ISSUE THREAD

**Issue by zakazai** [checkr/flagr#391]
I have a use case where I want to limit a segment using semantic versioning (e.g only enable feature when version >= 5.1.0, etc)

## Expected Behavior
I can specify constraint using semantic versioning on flagr UI

## Current Behavior
I don't think this is available yet. I've tried this at https://play.golang.org/p/9NYt1V1B_RB

**Update** : I think we can define it by creating multiple segments for each version that available for now

## Possible Solution
We can use https://github.com/blang/semver/ and maybe introduce a new operator perhaps at https://github.com/zhouzhuojie/conditions. 

## Context
I'm currently evaluating flagr and I have a use case to limit certain feature based on the app version.

**Comment by zhouzhuojie** [comment]
Thanks for reporting the feature request. I think semver maybe a little bit specific to be added for a generic condition's operator. I was thinking of supporting general functions in the constraints, that may work to cover the semver use case.

Before that, how about your application can parse the semver and pass the components as entity context? For example:

```
{
  "entityContext": {
    "major": 1,
    "minor": 0,
    "patch": 3
  }
}
```

And you can specify the conditions like `major <= 1` or `major <= 1 and minor >= 0`.

**Comment by zakazai** [comment]
Thanks for the prompt reply.

That's a good idea, I haven't thought about that. I think that'll be enough for my use case
