### ISSUE TITLE
Constrain using CONTAINS filter always fails. 

### ISSUE THREAD

**Issue by DoryZi** [checkr/flagr#400]
Contains will work well for srtings

When using contains constrain, it fails to detect that a entity_context parameter, actually contains the string.
We see that equal works fine, but contains seems to fail regardless of the value.

I.E.

`"msg": "Literal is not a slice of string: \"http://localhost:8000/products/31982887829566/confirmation/?funnel=start&site=because&did=1732a3747268a-02f8335de7751d-1b396256-13c680-1732a374727189&variant=31982887829566&addons_before=true&product_position=2&product_position_variant=29600123486278&addons=&trial_addons=&utm_content=taboola\"",
`

I've also tried to simplify in case there is some url encoding going:

` "msg": "Literal is not a slice of string: \"utm_content=taboola\""`

My constrain in the simplest definition as
Property: evaluate_url
CONTAINS
Value: "utm_content"

Here is the test request I sent in the simplest form:

```
{
  "entityID": "a1234",
  "entityType": "report",
  "entityContext": {
    "evaluate_url": "utm_content=taboola"
    
  },
  "enableDebug": true,
  "flagID": 2,
  "flagKey": "*************"
}

```

## Possible Solution
Not a go expect but I suspect that the way it's sliced and matches is incorrect.

## Steps to Reproduce (for bugs)
- Setup a flag with constrain, as per my example above
- Run the test in the Flagr UI with debug. Equal works fine, contains always fails.

1.
2.
3.
4.

## Your Environment

* Version used (`flagr version`):
* Server type and version:
* Operating System and version (`uname -a`):
* Link to your project:

**Comment by zhouzhuojie** [comment]
Related link: https://github.com/zhouzhuojie/conditions/issues/11#issuecomment-568574506

`CONTAINS` only works for `[array] contains item`, if you want substring, the regex operator `=~` can help.

**Comment by DoryZi** [comment]
Thanks! Amazing work on Flagr!
