### ISSUE TITLE
[feat] Support evaluation for all enabled flags in 1 call

### ISSUE THREAD

**Issue by zakazai** [checkr/flagr#406]
Provide new param/endpoint where client can get evaluation for all enabled flags in 1 API call

## Expected Behavior

Client can call Flagr once to get evaluation for all enabled flags

## Current Behavior

What I'm currently doing is perform request to server twice.
1. Get all enabled flags via `/api/v1/flags?enabled=true`
2. Post `/api/v1/evaluation/batch` with `flagIDs` param set from 1st call response

## Possible Solution

Some ideas that I can think of : 
1. Introduce new param (e.g `allFlag` in boolean) as option at `/api/v1/evaluation/batch`  where server can use it to return evaluation for all enabled flags. If `allFlag` is set then Flagr will ignore `flagIDs`, `flagKeys` and `flagTags` and perform its own lookup for all enabled flag then return the evaluation to client.
2. Introduce new endpoint (e.g `/api/v1/evaluation/all`) where Flagr will return evaluation for all enabled flags

## Context

I have an app that will get all feature flag from Flagr during splash screen. Currently the app needs to perform two API calls to get the evaluation for all flags. I think it'll be good if this process can be simplified to 1 call only.

**Comment by zhouzhuojie** [comment]
With the current tag support https://github.com/checkr/flagr/pull/369, is it possible for you to tag all the flags that matter and use tag-based batch evaluation? I would imagine eventually the requirement of `all flags` may need to be split into certain categories.

**Comment by zakazai** [comment]
yeah I think using tag would do that. My initial configuration setup was all flags are related with in-app feature only but later I realised I need to separate `all flags` between flags for my app and my backend services as well in the future.
