### ISSUE TITLE
Are flagIds mandatory in postEvaluationBatch?

### ISSUE THREAD

**Issue by innovation16** [checkr/flagr#422]
Hey Flagr Team, I wanted to know if flagIds are mandatory in postEvaluationBatch request.
Is there a way to get evaluation for all the active flags?
Also, is it possible to use a descriptive name instead of a flagId?

**Comment by zhouzhuojie** [comment]
https://checkr.github.io/flagr/api_docs/#operation/postEvaluationBatch

1. Either flagIDs, flagKeys or flagTags works for `postEvaluationBatch`, as long as there's enough information to resolve which flags to be used.
2. For all the active flags, the recommendation is to use flagTags, as discussed here https://github.com/checkr/flagr/issues/406
3. The `flagKey` can be updated once the flag is created, so you can use that to identify your flags.
