### ISSUE TITLE
Is Flagr suitable to long list of ID on a constraint list?

### ISSUE THREAD

**Issue by oliveiramiguel** [checkr/flagr#434]
I would like to use Flagr as [permission feature toggle](https://docs.getunleash.io/docs/advanced/feature_toggle_types).
Once a user send a payment to my system, I will add their ID to constraint list on a segment.

This list will get big, about 1M of ID. Is Flagr suitable for that use?

I'm sending a print to illustrate the use case. To add a ID to the list, I will use Flagr API.

![image](https://user-images.githubusercontent.com/1492592/109548955-0d3d0b00-7aac-11eb-9695-728f24b36c76.png)

**Comment by zhouzhuojie** [comment]
How about setting an attribute for your users, say "sent_payment", and pass that as context to flagr? and then you can set the constraint as `sent_payment EQ true`

**Comment by oliveiramiguel** [comment]
Thanks for your answer
I had thought of implementing it the way you suggested.
However, I wanted to see if it was appropriate to use Flagr in the way I described.
I would not like to add some attributes to my main database. I wanted to put this responsibility on Flagr.

**Comment by zhouzhuojie** [comment]
I think I have a few concerns with this approach, maybe flagr can consider supporting it, but for now, it's better for the client to think carefully about the evaluation pattern.

- Flagr keeps all the things in in-memory cache, may have a high memory footprint
- https://github.com/checkr/flagr/blob/master/pkg/entity/constraint.go#L19 may require a migration to support larger VARCHAR size (e.g. default gorm sets I think 64kb for `text`, may need to double check)
- Not super efficient to update/insert/delete some ids from this list of 1M IDs, every change is atomic and requires a whole write operation of 1M IDs

**Comment by oliveiramiguel** [comment]
I completely understood, thanks for the explanations
