### ISSUE TITLE
Use case for checking whether or not a flag is enabled for a user is unclear

### ISSUE THREAD

**Issue by ryexley** [checkr/flagr#436]
This is more of a question about documentation and usage than anything else. If there is a more appropriate place to ask questions like this, I was unable to determine where that might be, so please feel free to point me in the right direction of this is inappropriate here.

We're evaluating the use of Flagr as our feature flagging solution, and I've started working my way through the documentation. We have stood up an instance on Heroku and I've been able to get logged in to the admin UI and added a couple of flags. I can hit the `/api/v1/flags` endpoint to see a list of flags, but there is a case that I feel is missing here.

With other feature flag services that I've used, when you fetch the list of flags from the API, you provide a context, and often that context includes a user ID, email address, some other contextual data, all of which can be used to determine whether or not a given flag is enabled for that user in a given environment based on the configuration of segments for a flag, etc.

I can't seem to figure out a roughly equivalent behavior with Flagr, and I'm not really sure what I'm missing. I believe I've been through all of the documentation available, including the API documentation. The closest thing I've found is the ability to "evaluate" a flag, but I'm not sure if that's the same thing or not. From what I can tell, I can submit an HTTP `POST` to `/api/v1/evaluation`, and it will accept an `entityID`, `entityType` and `entityContext`. I was thinking perhaps this might be what I was looking for, but from what I can tell, given the response payload from that request, there is no `enabled` property in that response, so how would I know if the given `flagID` or `flagKey` was enabled for the given context or `entityID` in this case? Additionally, if this is the case, wouldn't I have to make an http request to the Flagr API _every single time_ I wanted to know if a given flag was enabled for a user? That seems a bit more chatty than I would prefer.

I'm hoping somebody can help me understand what I'm missing in terms of what a typical workflow looks like with Flagr, maybe just point me to some documentation that perhaps I'm missing?

Thanks so much.

**Comment by zhouzhuojie** [comment]
Yes, I think you can look for `variantID` or `variantKey` from the evaluation payload, which means which variant does the entity belong to.

If the variantID or variantKey is null, it means that the entity should not be rolled out in this flag - i.e. not included in this flag rollout.

If the variant ID or variantKey is not null, it means that the entity is rolled out according to your distribution settings. Usually the entity will fall into a segment you defined in the flag.

You can try with the debug console and try different context and flag configuration settings.

Let me know if it works for you.
