### ISSUE TITLE
Issue accessing flagr on kubernetes

### ISSUE THREAD

**Issue by stumueller** [checkr/flagr#469]
In the deployment yaml I have pulled the flagr image from checkr/flagr
I have configured FLAGR_DB_DBDRIVER and FLAGR_DB_DBCONNECTIONSTR to point to a mysql database - which does work.
I have configured the variable PORT to be 18000

I can see the pod has started and is able to talk to the database. I access the pod via httpproxy but this is not working. When trying https://fqdn.domain.com/flagr I get {"code":404,"message":"path /flagr/ was not found"}

my Deployment.yaml
kind: Deployment
apiVersion: apps/v1
metadata:
  name: flagr
  labels:
    app: flagr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flagr
  template:
    metadata:
      labels:
        app: flagr
    spec:
      containers:
        - name: flagr
          image: checkr/flagr
          resources:
            requests:
              cpu: "250m"
              memory: "64Mi"
            limits:
              cpu: "500m"
              memory: "128Mi"
          env:
            - name: PORT
              value: "18000"
            - name: FLAGR_DB_DBDRIVER
              value: mysql
            - name: FLAGR_DB_DBCONNECTIONSTR
              value: admin@testmysqlsrv:######@tcp(testmysqlsrv.mysql.database.azure.com:3306)/testmysql

my services.yaml
kind: Service
apiVersion: v1
metadata:
  name: flagr
spec:
  selector:
    app: flagr
  ports:
    -  port: 80
       targetPort: 18000

my proxy.yaml
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: frontend
spec:
  virtualhost:
    fqdn: fqdn.domain.com
  routes:
    - conditions:
        - prefix: /
      services:
        - name: web
          port: 80
    - conditions:
        - prefix: /api
      services:
        - name: webapi
          port: 80
    - conditions:
        - prefix: /odata
      services:
        - name: odata
          port: 80
    - conditions:
        - prefix: /flagr
      services:
        - name: flagr
          port: 80

Am I missing something in my proxy config?

**Comment by marceloboeira** [comment]
Hey, @stumueller 

Since you've rewritten the path to `/flagr` you need to inform flagr of that too...  so set the variable `FLAGR_WEB_PREFIX` to `/flagr` so that flagr knows which path it should respond to requests:

From the [flagr config](https://checkr.github.io/flagr/#/flagr_env): 
```
    // WebPrefix - base path for web and API
    // e.g. FLAGR_WEB_PREFIX=/foo
    // UI path  => localhost:18000/foo"
    // API path => localhost:18000/foo/api/v1"
    WebPrefix string `env:"FLAGR_WEB_PREFIX" envDefault:""`
```

You will have the UI there:
https://fqdn.domain.com/flagr

And API:

https://fqdn.domain.com/flagr/ap1/v1/...

Let us know if that works and you can close this issue!
